name: mne_eeg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mne
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - ipython
  - pyqt
  - mne-qt-browser
  - edfio
  - pip